-- Execute no SQL Editor do Supabase

-- 1) Tabela principal dos conteudos
create table if not exists public.conteudos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  legenda text default '',
  data text not null,
  tipo text not null check (tipo in ('estudos', 'cartas')),
  url text not null,
  created_at timestamptz not null default now()
);

-- 2) Tabela simples de admin (credencial solicitada)
-- Observacao: para producao, prefira hash de senha e fluxo real de auth.
create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  created_at timestamptz not null default now()
);

insert into public.admin_users (username, password)
values ('adm', 'admin')
on conflict (username) do update set password = excluded.password;

-- 3) RLS
alter table public.conteudos enable row level security;
alter table public.admin_users enable row level security;

-- Leitura publica dos conteudos
drop policy if exists "Public read conteudos" on public.conteudos;
create policy "Public read conteudos"
on public.conteudos
for select
to anon, authenticated
using (true);

-- Escrita apenas para usuarios autenticados do Supabase Auth
drop policy if exists "Authenticated insert conteudos" on public.conteudos;
create policy "Authenticated insert conteudos"
on public.conteudos
for insert
to authenticated
with check (true);

-- Nao expor tabela de admin diretamente ao cliente anonimo
drop policy if exists "Block anon admin_users select" on public.admin_users;
create policy "Block anon admin_users select"
on public.admin_users
for select
to anon
using (false);

-- Permitir select para authenticated (uso interno/dashboard)
drop policy if exists "Authenticated read admin_users" on public.admin_users;
create policy "Authenticated read admin_users"
on public.admin_users
for select
to authenticated
using (true);

-- 4) Storage bucket para PDFs
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('pdfs', 'pdfs', true, 10485760, array['application/pdf'])
on conflict (id) do nothing;

-- Leitura publica dos arquivos PDF
drop policy if exists "Public read pdfs" on storage.objects;
create policy "Public read pdfs"
on storage.objects
for select
to public
using (bucket_id = 'pdfs');

-- Upload apenas para authenticated
drop policy if exists "Authenticated upload pdfs" on storage.objects;
create policy "Authenticated upload pdfs"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'pdfs');
